name: cf-mysql

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mysql
  instances: 2
  azs: [z1, z2]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10000
  jobs:
  - name: mysql
    release: cf-mysql
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
          cluster_health:
            password: ((cf_mysql_mysql_cluster_health_password))
          galera_healthcheck:
            endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))
            db_password: ((cf_mysql_mysql_galera_healthcheck_db_password))
  - name: smoke-tests-user
    release: cf-mysql
    properties:
      cf_mysql:
        smoke_tests:
          db_password: ((cf_mysql_smoke_tests_db_password))

- name: arbitrator
  instances: 1
  azs: [z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - release: cf-mysql
    name: arbitrator
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
          galera_healthcheck:
            endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))

- name: proxy
  instances: 2
  azs: [z1, z2]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: proxy
    release: cf-mysql
    properties:
      cf_mysql:
        proxy:
          api_password: ((cf_mysql_proxy_api_password))
    provides:
      mysql-database:
        as: mysql-database
        shared: true

- name: bootstrap-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: bootstrap}

- name: rejoin-unsafe-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: rejoin-unsafe}

- name: verify-cluster-schemas-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: verify-cluster-schemas
    release: cf-mysql
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
          galera_healthcheck:
            endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))

- name: smoke-tests-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: smoke-tests
    release: cf-mysql
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
        proxy:
          api_password: ((cf_mysql_proxy_api_password))
        smoke_tests:
          db_password: ((cf_mysql_smoke_tests_db_password))
          standalone_tests_only: true

variables:
- name: cf_mysql_mysql_admin_password
  type: password
- name: cf_mysql_mysql_cluster_health_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_db_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_endpoint_password
  type: password
- name: cf_mysql_proxy_api_password
  type: password
- name: cf_mysql_smoke_tests_db_password
  type: password

releases:
- name: cf-mysql
  url: https://bosh.io/d/github.com/cloudfoundry/cf-mysql-release?v=36.18.0
  version: 36.18.0
  sha1: 77fdcbac486994bb8170a88f29a599ce848ccc66
- name: bpm
  url: ""
  version: latest
  sha1: ""
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3586.71"
